# Generated by Django 4.0.1 on 2022-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='blog/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
