# Generated by Django 4.0.1 on 2022-03-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
