# Generated by Django 4.0.1 on 2022-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='Career/images/')),
                ('job_ads', models.TextField(verbose_name='Job advertisement title')),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
    ]
