# Generated by Django 4.0.1 on 2022-04-03 10:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='job_ads',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
