# Generated by Django 4.0.1 on 2022-03-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_career'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cv',
            new_name='Resume',
        ),
    ]
