# Generated by Django 4.0.1 on 2022-04-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_remove_resume_phone_alter_resume_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='image',
            new_name='background',
        ),
    ]
